spring.application.name=AutoMeta
// server.port =8080

# youtube api key
youtube.api.key=AIzaSyBh92C-sT9h8TWJOoIGqoI8hf_C3WmiYqI
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.api.search.url=${youtube.api.base.url}/search
youtube.api.videos.url=${youtube.api.base.url}/videos

# Max number of related videos to fetch
youtube.api.max.related.videos=3